ekf_filter_node:
  ros__parameters:
    frequency: 15.0
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # Wheel Odometry (from Pico Bridge)
    # We trust the velocities (X linear, Z angular)
    odom0: /odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  false, false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false

    # IMU Data (from imu_filter_madgwick)
    # We trust the absolute yaw orientation and Z angular velocity
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  true,  false, false]
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true
